travis:
  secure:
    BINSTAR_TOKEN: Ht8/z4DOAWOvzsrWIc/kvisyF9qwDnf+RG/5OK7B6ZFrrSvMbdoT8fR6yOBhs2Zr098fGboUTxkTeQYQ2cBFseYejWgWzXxOq7YKAqpm7uV9ZoCliffsz4q2q7CvSvclQCE03ZWhMqdH1xZP/g4zt5fHtDDC2CQhv2oij3xqy9CLCc0nP2SiuNQuSEbulAJAoz6rsJGgOtJOqQzwd2Ao3g6GU3IAWb+MIW+NOMV9quk37RI1CgDiK8hfqPSADymORYgL9Pv9bhtH75AfLcpWfyyG+fzT/5eBMEhDzmHMT3Ks0ebTw4d/IpK0VrcqCEpsu3aRGOJ+/RllIJk/oVD4QfSlO8d+dFPJQEYz+I5CnNxcVVLkMPZCcJvuolAeQ2sdoLVWuxFtUVsz17siS5cu1N9Udbgo1gQ52RyC0ms8VCr45h8SS6eesONhw0xyLnpyJspgHdvFLqjEDnePSKjg5oi44bKkJoXYPP9nmPXjVMDr+yJZRznsCCz29Yp4zu0bMfaJGlQNV8qrvt7wUuTNLQX7qzK73EsG4pXCQIyOSf5WztYVTji92p4U2krvUXSjKBGLVjvpgPNGC/wou03lyfYiKETluy6aAz6CMXRS+1gkVoo4cQqvzcrpY3HZN68F1hA7Lk12EEab3H++7dP6hC8rfKBf0Px9iVha0Z/6s28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
